<?php
bolt_decrypt( __FILE__ , 'TCbwjK'); return 0;
##!!!##Mi8yL5OGkoqYlYaIikVmlZWBcpSJipGYYDIvMi+amIpFbpGRmpKOk4aZioFphpmGh4aYioFqkZSWmoqTmYFrhoiZlJeOipiBbYaYa4aImZSXnmAyL5qYikVukZGako6ThpmKgWmGmYaHhpiKgWqRlJaaipOZgXKUiYqRYDIvMi+IkYaYmEVyjp2Ok5huk4uURYqdmYqTiZhFcpSJipEyL6AyL0VFRUWamIpFbYaYa4aImZSXnmAyL6IyLw==